nav:
  - Introduction: index.md
  - Design History: history.md
  - Design Inputs: inputs
  - Design Outputs: outputs
  - Design Verification: verification
  - Design Changes: changes.md
  - Tools / Troubleshooing: tools
  - glossary.md