nav:
  - Design Overview:
    - Project Introduction: index.md
    - Quick Start Guide: quickstart.md
    - Development History: history.md
  - Design Inputs: inputs
  - Design Outputs: outputs
  - Design Verification: verification
  - Design Changes: changes
  - glossary.md